### ISSUE TITLE
OSX auto-adjusts recording volume

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#117]
Feedback from user: https://scrimba.com/@aaronshaf

"The other difficulty I can think of right now is the recording volume issue. OSX (or perhaps your app via JS?) is auto-adjusting the recording volume, and the audio ends up "hot". I'd like to "fix" the recording volume somehow."

**Comment by aaronshaf** [comment]
Is the app setting `.gain` for recording?

I see:

```
prototype.updateGain=function(){var t=this.getRealVolume();if(this._context){this.gainNode().gain.value=t}
```

... in the minified client, but assume this may be for manual playback volume control.

**Comment by somebee** [comment]
Hey. The method is setting the gain for playback. I'm not sure how to fix. We are thinking about improving the post-processing by auto-adjusting the volume across clips, and to allow setting the volume manually. The downside then will be that the audio must be processed in WebAudio before sending it to the server (on publish) which means we will need to send raw PCM data (_huge_ files compared to opus), or encode it on the client (cpu-intensive, takes a long time).

Is it adjusting the volume differently per clip, or inside each individual recordings as well? What kind of microphone are you using (if external)?

**Comment by aaronshaf** [comment]
It looks like you can set `googAutoGainControl` and `mozAutoGainControl` to false with `getUserMedia`, i.e. https://cl.ly/0Y0u1A3F133B

**Comment by aaronshaf** [comment]
See related: https://github.com/mattdiamond/Recorderjs/issues/75

**Comment by somebee** [comment]
Nice find! Do you think we should disable googAutoGainControl only, or does it make sense to disable the others as well? Won't be able to really test the quality changes today, but I can deploy a build with `AutoGainControl: false` asap

**Comment by aaronshaf** [comment]
The ability to set `googAutoGainControl` and `mozAutoGainControl` to false -- that alone -- would be a great. The others look reasonable for defaults.

**Comment by somebee** [comment]
Working on this now. It seems as if chrome does not allow setting autoGainControl independently. The only way to disable it (and all other effects) is to set echoCancellation to true.

https://addpipe.com/blog/audio-constraints-getusermedia/

**Comment by aaronshaf** [comment]
That is counterintuitive. Did you mean "set echoCancellation to [false]"?

If I want to disable autoGainControl, I should turn echoCancellation on? 

Anyways, thanks for your work on this!

**Comment by somebee** [comment]
You are of course right, I meant setting echoCancellation to false 👍 

The api for setting audioConstraints seems very flaky and ever-changing. Setting googAutoGainControl (and the other goog*) constraints does not seem to do anything, and if you try to set them as mandatory they raise a "Constraint not found" error - at least on Chrome 63 (mac). [This issue](https://bugs.chromium.org/p/chromium/issues/detail?id=792391&q=googAutoGainControl&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) seem to suggest otherwise, so I might need to test some more. 

Right now we only allow setting the constraints that are reported back from the browser in [mediaDevices.getSupportedConstraints](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getSupportedConstraints).

There are [many other issues](https://bugs.chromium.org/p/chromium/issues/list?can=2&q=component%3ABlink%3EMediaRecording+&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids) with the MediaRecorder API in chrome. We've recently enabled recording in FF, and it has better support for constraints, and fewer issues. So you might want to try it and see if it works for you.

**Comment by aaronshaf** [comment]
When echo cancellation off, my volume level has remained stable / consistent (doesn't fluctuate). Working much better. Thanks again!

**Comment by Pistus** [comment]
Closing as stale issue.
