### ISSUE TITLE
`1x` jumps to `2x`

### ISSUE THREAD

**Issue by isomorphisms** [scrimba/community#153]
watching https://scrimba.com/casts/cast-1953 on a Windows 10 Edge browser, I clicked on "speedup" and it immediately jumped to `2x`. Cannot rescale.

**Comment by isomorphisms** [comment]
Also cannot resize the browser/viewer window from 100%.

**Comment by isomorphisms** [comment]
`2x` speed and `10s` jumps are not the most useful options. Generally 110% to 130% speedups are the most useful range. (Would be nice in this case if `sox` can smooth this speaker's consonants but that would be very fancy.)

**Comment by judofyr** [comment]
Interesting. It's supposed to be a slider that shows when you hover.

**Comment by mrestko** [comment]
I'm having the "stuck on 2x speed" issue in Chrome 63 on Windows 10.

**Comment by somebee** [comment]
Very strange. Everything plays back at 2x, or is the control itself just stuck at 2x?

**Comment by mrestko** [comment]
Play speed and the slider were both stuck on 2x. I had to clear all cookies for the page before it would go back to normal speed.

**Comment by scanf** [comment]
Hmm, the problem is not jumping but the slider is not even rendered on internet edge. See screenshot below. I will look into this, thanks.

![Screenshot 2019-12-04 at 09.55.54.png](https://gitspeak.com/-/nUp3p9Lb3d170/Screenshot%202019-12-04%20at%2009.55.54.png)![Screenshot 2019-12-04 at 09.55.50.png](https://gitspeak.com/-/nUp3p9L29cfc7/Screenshot%202019-12-04%20at%2009.55.50.png)

**Comment by scanf** [comment]
Please use the latest version of Microsoft Edge http://microsoft.com/edge

Thanks.
