### ISSUE TITLE
Audio out of sync

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#155]
Check out 2:07 in this cast. The audio is a bit off, if you compare it with the typing:

https://scrimba.com/c/c7Jqdfa

**Comment by somebee** [comment]
Are you listening with Bluetooth headphones? If not - what mic did you record with etc?

**Comment by perborgen** [comment]
It's happening without headphones as well. Recorded with the Blue Raspberry mic.

**Comment by perborgen** [comment]
Is this something which likely can be fixed in the database @somebee or will I have to re-record it?

**Comment by perborgen** [comment]
The audio is about 1.5 seconds ahead of the events/stream.

**Comment by somebee** [comment]
Looking into it. We can fix this one by offsetting the audio-track manually, but we need to figure out the root cause as well :)

**Comment by somebee** [comment]
This is most likely caused by an issue where the MediaRecorder drops audio-frames when CPU is under high load. Let's file another issue if the problem persists. We have implemented some fixes for better audio synchronisation on published casts, but if the audio is off when playing back using webaudio as well, the problem likely exists in the audio file itself, and is difficult to do anything about.
