### ISSUE TITLE
"feedback" and "chat" buttons on navbar, is non functional in Firefox.

### ISSUE THREAD

**Issue by ivarsu** [scrimba/community#166]
Running latest stable version of Firefox(57.0.1), the rest of the page works excellent.

**Comment by judofyr** [comment]
@somebee It seems like when there's an `<a>` inside a `<button>` we don't receive the click/touch event on the link, but on the button instead. Not quite sure if that's caused by something we do or if it's the default behaviour in Firefox (maybe it's the correct behaviour in the standard for all I know).

**Comment by judofyr** [comment]
Apparently it's not legal to have interactive content inside a `<button>` so we need to tweak the markup. I've created a pull request in Uxa here: uxa/uxa#2.
