### ISSUE TITLE
Audio starts late (lesson stays silent for a few seconds)

### ISSUE THREAD

**Issue by aaronshaf** [scrimba/community#186]

**Comment by somebee** [comment]
If it happens on your own cast - don't worry. We should definitely fix it, but it happens because we use webaudio to play back your own casts (to be able to support high precision audio editing++). Other viewers will also use webaudio if the cast is unpublished.

Still, we should wait for the audio to load in this scenario as well, and indicate this in the ux.

**Comment by aaronshaf** [comment]
In my opinion, this is worth extra attention. Makes for a bad first-time experience.

**Comment by somebee** [comment]
This is now fixed. Word of warning; buffering your own casts will take a lot longer than it does for your viewers. While the viewers are streaming a regular audio file, you preload all the audio and decode it into webaudio, which takes a while. So, while you may wait 5-10 seconds before your cast starts playing, your viewers will hardly get any buffering at all.
