### ISSUE TITLE
disable normalize.css

### ISSUE THREAD

**Issue by jwssnr** [scrimba/community#264]
Hi. With my students I usually do not use normalize.css, so it would be great to have the possibility for switching it on and off.

**Comment by zaydek** [comment]
@jwssnr so I came up with a clever technique. I tried to override the CSS reset in place with `!important` and that led to more problems, so instead I used CSS's specificity (https://specificity.keegan.st/) behavior to correct it. At first, I tried targeting everything with a `* { ... }` rule but that didn't work so instead I did `html * { ... }` and that allowed me to override any default behaviors because I have more specifying power.

**Comment by judofyr** [comment]
normalize.css is also for having consistent playback across different browsers. If you record a screencast with your brower's default stylesheet, it might not look the same when you play it in a different browser. Do you know if there's an alternative CSS-stylesheet that ensures e.g. Chrome's default style across browsers?

**Comment by jwssnr** [comment]
@zaydek @judofyr To learn css it is important to have a browers native rendering. This includes differences from one browser to another. My opinion. Also when I do real work (not in the class) I’m one of those who don’t use resets or normalizes out of the box. I don’t like te idea to overwrite something which does not necessarily have to be there.

**Comment by judofyr** [comment]
Right, but the problem is that if you record a screencast in Chrome, the user who watches in it Firefox won't see the exact same thing as you do. This can cause confusing issues if you comment on some specific spacing, and that spacing happens to be different between browsers. The spacing differences can also cause a completely different layout (if it causes a box to overflow), and then the recorded mouse cursor will be played back in the wrong place.

We're not opposed to having a way of disabling normalize.css, but you need to be aware of these issues when you record.
