### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by MrChriZ** [scrimba/community#414]
I'm trying to follow a few tutorials that use fetch such as 
https://scrimba.com/p/p4Mrt9/cKLyeuy

However in playground mode the fetch requests aren't working.  If I bring up the chrome console I find messages like this:
Access to fetch at 'https://fcctop100.herokuapp.com/api/fccusers/top/alltime' from origin 'https://run.scrimba.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by rokublac** [comment]
If you look at the network tab in your chrome console, you should see that you're hitting a `404` when requesting from that API.  I tested the code on one of my APIs and it seems to work.
```javascript
const apiUrl = 'https://twauapi.herokuapp.com/characters/1';

async function fetchAPI() {
    const response = await fetch(apiUrl);
    const json = await response.json();
    
    console.log(json); // no array index since it's fetching one data
}

fetchAPI();
```
So try and mess around with some other APIs and see. I'm fair sure it's just that URL you're trying to fetch from. Good luck!

**Comment by MrChriZ** [comment]
Oops!  Bad example!  Could have sworn that one was working earlier
This one definitley has a working API:
https://scrimba.com/p/p7P5Hd/c79Jask
Uses the API https://swapi.co/api/people/1
Again:
Access to fetch at 'https://swapi.co/api/people/1' from origin 'https://run.scrimba.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by rokublac** [comment]
Hmm, interesting because I can make a request to the API in that cast with his code. Can you please check your network tab in chrome console and tell me what's going on in there? Make sure you clear the console before you run the code since there's going be a lot of requests.

I'm just curious about the last request so just skip down to that one.
<img width="595" alt="22" src="https://user-images.githubusercontent.com/33192458/59924659-939cef00-9479-11e9-913e-0748c490da74.PNG">

**Comment by MrChriZ** [comment]
Not sure if this helps:
![image](https://user-images.githubusercontent.com/3593276/59926631-9e806100-9432-11e9-983a-76ff39d59115.png)

**Comment by MrChriZ** [comment]
When I click on the red 1:
![image](https://user-images.githubusercontent.com/3593276/59926684-bbb52f80-9432-11e9-80e4-bad9261fdc42.png)

**Comment by rokublac** [comment]
Unfortunately I am not too sure why you're experiencing a CORS error. Maybe try on another browser? You can also try this [Allow-Control-Allow-Origin Chrome extension](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi) and see if that works, just make sure to disable it when you're not testing API requests since some sites like YouTube may not work with that extension on.

**Comment by MrChriZ** [comment]
Interesting.  I switched to Firefox and the issue was not present.
I tried turning off all plugins to Chrome and the issue remained.
I have a tendency to run Chrome Beta (and forget I am doing so) so dropped back to regular chrome and wallah - it works!

So obviously an environment issue - thanks for assisting.

**Comment by MrChriZ** [comment]
Sorry going to reopen this one.  What ever it was that was in the beta seems to have made it into the release version of Chrome now.  I've tested this on Linux and Windows version of Chrome and see the same thing.

**Comment by MrChriZ** [comment]
No hang on I lie - it's a problem with the lesson - it's using an old URL that doesn't work any more.
