### ISSUE TITLE
Playgrounds are broken for some users

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#452]
https://spectrum.chat/scrimba/general/scrimba-playground-doesnt-work-on-chrome-and-safari~1ac7a2ef-4394-4e27-ac24-6086c964a210

**Comment by arimourao** [comment]
It is not working also on Firefox. I tested on 60.9.0esr (64-bit)

**Comment by perborgen** [comment]
Hmm... I'm getting it to work on FireFox. Can you elaborate on what happens when you try to create a Playground?

**Comment by perborgen** [comment]
A screenshot would have been great!

**Comment by scanf** [comment]
@perbogen This bug is easily reproducible with the version @arimourao is using. You can download it here [https://www.mozilla.org/en-US/firefox/60.8.0/releasenotes/](https://www.mozilla.org/en-US/firefox/60.8.0/releasenotes/)



As soon as you hit refresh in the mini-browser, instead of seeing a rendering of the current playground a empty mini-browser is rendered, see screenshot below

![Screenshot 2019-10-11 at 12.01.32.png](https://gitspeak.com/-/nUp38eL6e60dd/Screenshot%202019-10-11%20at%2012.01.32.png)

The logs do show some type errors, maybe it's related?

```
TypeError: t._sw is undefined[Learn More] __sw__bridge.js:1196:1 
TypeError: t._sw is undefined[Learn More] __sw__bridge.js:1196:1 
```

**Comment by Pistus** [comment]
Thanks @scanf, I have reproduced it locally.



So with an update last week we changed some of the file handling logic to use service workers. Seems like this is less robust than hoped for. For example it seems that service workers are disabled in the Firefox ESR releases.



Download link for firefox ESR version that triggers error: https://download.mozilla.org/?product=firefox-esr-latest-ssl&amp;os=osx&amp;lang=en-US

**Comment by rmgoldberg24** [comment]
Hello,

I just randomly started experiencing this today in the middle of a lesson. "Preview" is always blank when in edit mode after refreshing, for multiple lessons. I've tried Chrome and Safari, neither are working. I tried clearing the cache and am still experiencing the issue. It started within React Bootcamp > React Context > Challenge: Context Practice One. Chrome is up to date (Version 88.0.4324.182 (Official Build) (x86_64)).

I love your application and look forward to being able to use it again.

Many thanks,
Robyn

**Comment by perborgen** [comment]
@rmgoldberg24 Sorry about this, it was a bug, but it should have been fixed by now. Let us know if you ever experience this again.

**Comment by rmgoldberg24** [comment]
Yes it is working again today, thank you so much for your help! It is much appreciated.

Best,
Robyn

**Comment by rahalrazika** [comment]
![image](https://user-images.githubusercontent.com/45298820/141676133-367f0ad4-4faf-4363-a81d-dd9cd767564d.png)
Hi anyone could help me with what can I do with the scrimba website to get it to work.
Best,
Raza

**Comment by FreezyDoesIt** [comment]
I'm experiencing the same issue today as originally posted by @aalemayhu .

**Comment by biofilos** [comment]
I am also experiencing the same issue with Firefox 94.0

**Comment by averloon** [comment]
I have the same error when I use Firefox 98.0.2 64Bit. This is kinda frustrating

**Comment by s-gbz** [comment]
Same on Firefox 101.0 for Linux.

```
Failed to get service worker registration(s): Storage access is restricted in this context due to user settings or private browsing mode
```

**Comment by snoozleEmily** [comment]
I'm getting a similar problem, but instead of getting the preview page blank, it only appears the elements that were already there. It doesn't show any of the code I put in. I'm using Chrome version 103. Here's a screenshot if it helps: 

![issueScrimba](https://user-images.githubusercontent.com/105649387/176548149-8d38ef70-2425-47ee-9708-7f3e5cf775e3.png)
