### ISSUE TITLE
distracting mouse random movements

### ISSUE THREAD

**Issue by gaby64** [scrimba/community#477]
whoever thought it was a good idea to have the instructor mouse do random curved movements is evil

it is really distracting, please kill this feature

seems its not widespread, this one does it 
https://scrimba.com/p/pV5eHk/cGym4Ta

**Comment by rokublac** [comment]
I don't think anyone gave directions for the instructor to make those erratic cursor movements 😆

Sorry to hear it's distracting you but it seems like it is only isolated to that course (majority of the casts are fine). Most likely related to the instructor's side of things rather than a Scrimba feature.

**Comment by gaby64** [comment]
its not the instructor, these are movements between the actual movements

**Comment by perborgen** [comment]
These are related with how the cast was recorded, and is not something we can fix in post production at the moment. Sorry about this. Closing this issue now.
