### ISSUE TITLE
Responsive Design not so responsive

### ISSUE THREAD

**Issue by nmichalakis** [scrimba/community#567]
Hi, i am interested in buying a 6 or 12 month subscription plan for deepening my knowledge with any course that is related with the Front End Path (https://scrimba.com/learn/responsive + react + ui bootcamp etc.)
But i see that your "responsive" (mobile first?) version of the website is not so mobile - smartphone "friendly" :).
I believe that this "combo" css class is the problem` section.topic.d3tapub:not(#_) should have a zero padding - x (left and right).`
probably a media query for "small devices" could fix it.
```
@media only screen and (max-width: 576px) {
  .section.topic.d3tapub:not(#_)  {
    padding-left: 0;
    padding-right: 0;
  }
}
```
![Screenshot 2020-12-27 at 1 37 17 PM](https://user-images.githubusercontent.com/25632631/103170015-93896680-4849-11eb-9f86-d3c833a7c70e.jpg)
![Screenshot 2020-12-27 at 1 37 48 PM](https://user-images.githubusercontent.com/25632631/103170017-971ced80-4849-11eb-99b8-3a076abe856b.jpg)
![Screenshot 2020-12-27 at 1 37 28 PM](https://user-images.githubusercontent.com/25632631/103170022-9d12ce80-4849-11eb-983d-0d0dcf2d4fba.jpg)
![Screenshot 2020-12-27 at 1 44 40 PM](https://user-images.githubusercontent.com/25632631/103170031-b74cac80-4849-11eb-92e9-6053fdb98bd0.jpg)

**Comment by Pistus** [comment]
Thanks for reporting - I made some tweaks to make the front page work better on small devices. It is not perfect but as I know that we will redo that page in the near future with a new developer I will leave it for that process.

Since we are using v2.imba.io the change I did was set the default from 14 * 0.25rem to 4 * 0.25rem and adding a modifier for @lg (viewport >1024px.) like this:

**from:**
```
css section.topic
	px:14
```


**to:**
```
css section.topic
	px:4 @lg:14
```

I also adjusted some font sizes and other margins.
