### ISSUE TITLE
Content overflowing

### ISSUE THREAD

**Issue by saivukkem** [scrimba/community#592]
![505DDF60-15A4-435E-91DA-99E2F4FC935D](https://user-images.githubusercontent.com/69037101/116446128-8d82b100-a84e-11eb-8be1-bfcef1043e75.jpeg)

Highlighted part in the attached image is overflowing in the All Courses page.

**Comment by saivukkem** [comment]
Device - iPhone 12 Pro Max
Browser - Safari

**Comment by a-developer-and-her-mac** [comment]
I also have the same issue when using Chrome, on a mac. When playing around with the dev tools, it seems that the fix for mobile is removing the max-height for the container. Though when you do that it messes up the height of the container for desktop, however, I assume a media query would fix that.

**Comment by Pistus** [comment]
Yeah, it is not a well built component.. I fixed the content overflow some weeks ago and the component will be rewritten as a horisontal menu in the coming weeks.
