### ISSUE TITLE
Revision History / Revert

### ISSUE THREAD

**Issue by cavemansspa** [scrimba/community#63]
Are there any plans to provide reverting back to a previous version of the screencast?  I know a few people including myself that spent some time on making a screencast that then get's into a state that's busted and it seems that the only solution is to start over from scratch.

If you can go back to a recent working version, that would help.

**Comment by perborgen** [comment]
Hey @cavemansspa ,

Thanks for submitting this issue! At the moment you should be able to scroll back in your timeline (however, we're planning to remove this timeline, and only show timelines on replay).

Two questions:

1.
Are you talking about cases where the casts are completely broken (e.g. the player turns all black)?

If it's not all broken, then you can try to clone it, and see if the clone works any 
better than the original.

2.
Also, could you provide a link to a cast it has happened with?

This will help us identify what the problem was caused by, so that we can fix it.
