### ISSUE TITLE
Bug: It is possible to break projects

### ISSUE THREAD

**Issue by BlackCapCoder** [scrimba/community#70]
I am working on reverse engineering your protocol so this is entirely my fault, and it may or may not be possible to do this in the vanilla editor; but you might want to check the data from the client server side to make sure it is not corrupt, which could occur naturally if the user loses internet connection or power.

The actions that caused this was a replace command of the entire css file with exactly 255 bytes (as if the entire file was already selected in the editor, and then 255 bytes was pasted), followed by a long string of write commands (as if the user had typed in the rest), all in the same update message to the server.

The gray text is the code preview that normally appears before monaco boots. Switching file only partially works. Changes to the documents are not saved.

Link to the broken project: https://scrimba.com/casts/cLpLnUQ

#### Images
![image 1](https://i.imgur.com/3Q17YQ7.png "image 1")
![image 2](https://i.imgur.com/uwTXBcH.png "image 2")
![image 2](https://i.imgur.com/V5byrRm.png "image 3")

**Comment by judofyr** [comment]
How did you create the messages? Was it through automating the UI (i.e. running our client code) or did you build them yourself? The action at index 11737 is: `InsertText: [2, {}, 1, " "]` which is invalid since `{}` isn't a valid line number.

At the moment we're not going to implement server-side validation. If you push invalid packets to your own stream you can indeed break your cast. We probably will add better error detection on the client-side/player so that you get a proper message when you visit a broken cast.

Loss of internet/power shouldn't be able to cause these issues though since we always queue packets locally and push everything together. You should never be able to have packet loss in the middle of the stream.

**Comment by BlackCapCoder** [comment]
I did not use your client code, so this is indeed entirely my fault. I thought I'd just give you a heads up because server side validation is usually best practice.
Feel free to close this issue.
